apiVersion: v1
kind: Service

metadata:
  name: service-desk-uptime-monitor
  namespace: uptime-monitor

spec:
  type: ClusterIP

  selector:
    app: service-desk-uptime-monitor

  ports:
    - name: http
      port: 8000
      targetPort: http